name: Build XbfDecompiler

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Retarget to .NET 4.8
        shell: pwsh
        run: |
          Get-ChildItem -Recurse *.csproj | ForEach-Object {
            $content = Get-Content $_.FullName
            $content = $content -replace '<TargetFrameworkVersion>v4.5</TargetFrameworkVersion>', '<TargetFrameworkVersion>v4.8</TargetFrameworkVersion>'
            Set-Content $_.FullName $content
          }

      - name: Restore NuGet packages
        run: nuget restore XbfDecompiler.sln

      - name: Build solution
        run: msbuild XbfDecompiler.sln /p:Configuration=Release /p:Platform="Any CPU"

      - name: Upload Artifact
        uses: actions/upload-artifact@v6
        with:
          name: XbfDecompiler-Binary
          path: |
            XbfDecompiler/bin/Release/
            LibXbf/bin/Release/
